New blog post
tdex-network/dev-portal pull request #16
Opened 2021-08-20 13:01 UTC by kcoax

Explaining how to use one-click deployer

2021-08-20 13:05 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +As a first step it is required toobtain aws access and secret keys. Best practice is to create new user in AWS IAM. Proceed with opening AWS IAM users page, and click on Add user. Provide user with n
```suggestion
As a first step it is required to obtain aws access and secret keys. Best practice is to create new user in AWS IAM. Proceed with opening AWS IAM users page, and click on Add user. Provide user with name, and below for the Access type select Programmatic access. Next, make sure that your AWS account(access key) has all required privileges to create EC2 instances and S3 access. 
```

2021-08-20 13:08 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +title: Automate TDex deamon with terraform
```suggestion
title: Deploy a TDEX Daemon to AWS with Terraform
```

2021-08-20 13:08 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +slug: tdex-terraform-automation
```suggestion
slug: tdex-terraform-deploy
```

2021-08-20 13:09 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +author_title: Maintainer of TDEX Network
```suggestion
author_title: TDEX Contributor
```

2021-08-20 13:09 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +tags: [terraform, automation, tdex]
```suggestion
tags: [terraform, automation, tdex, deploy]
```

2021-08-20 13:10 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +As a first step it is required toobtain aws access and secret keys. Best practice is to create new user in AWS IAM. Proceed with opening AWS IAM users page, and click on Add user. Provide user with n
Please would be nice to have screenshot of AWS console at least, ie. how to get secret/access key etc..

Better to describe each step with bullet points and separate sections for better readability

2021-08-20 13:12 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +./deploy.sh aws_access_key aws_secret_key aws_region aws_ami ssh_public_key_path ssh_key_name IP_ADDR https://example.com/explorer aws_s3_my_backup_bucket
Why not using read and making interactive prompt to ask each parameter? this is a bit clunky and prone to error for users with basci command line skills

2021-08-20 13:13 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +Enabling the unlocker is as easy as creating a file containing the same password used to init your daemon's wallet and exporting its path in the PWD_PATH variable, like for example:
Not clear where this should be exectuted. Will need the user to login via ssh in the remote machine etc..

2021-08-20 13:13 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +$ docker exec -it tdexd unlockerd
I would leave out the unlocker option, maybe is a bit difficult

2021-08-20 13:19 UTC, tiero requested changes
I think in general this blog post should be much more than some words on top of the tdex box, therefore we need to think about users with very entry level command line skills, so we dont need to leave out any steps and think they are known.

Also, we must be OPINIONATED and give out what we suggest as professional deployment, therefore we MUST have the S3 backup option enabled (and instructions on AWS if necessary) and most importantly the onion hidden service, so we can actually expose the tdex daemon to the world.

Last section should be about controlling the tdex daemons with the CLI (. ie. `tdex listmarket`) so an alias should be added

2021-08-20 13:23 UTC, kcoax commented
I started working on changing the text to be more readable and will change the script to **read** inputs, not a big problem. 
I will also add support for Onion in automatic deployment. 

Regarding the controlling of tdex daemons etc, I think we might combine it with unlocked on a separate blog post? @tiero

2021-08-20 14:59 UTC, tiero commented
> Regarding the controlling of tdex daemons etc, I think we might combine it with unlocked on a separate blog post? @tiero

Yes we can point to docs on how to init, unlock, deposit funds etc..

Poin is that user is running terraform from his local machine, is not quite obvious how from this blog post to go ahead and follow the docs on those matters, therefore we need to mention how the user controls. Simplest thing is to tell the user to SSH in the EC2 and use `tdex`alias (if we add automatically ie. `alias tdex="docker exec -it tdexd tdex "`)


Ohter option is to teach the user to install the `tdex` CLI in the local machine and do the macaroons pairing (more difficult maybe)

2021-08-31 09:08 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +As a first step it is required toobtain aws access and secret keys. Best practice is to create new user in AWS IAM.
```suggestion
As a first step it is required to obtain aws access and secret keys. Best practice is to create new user in AWS IAM. 
```

2021-08-31 09:30 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +On the AWS AMI Marketplace, find Ubuntu 18.04 public AMI, accessible in the region you are planing to deploy service and copy it's AMI ID.
why not ubuntu 20?

2021-08-31 09:31 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +To run deploy please prepare: \
It does not look good, maybe put in markdown quotes?

<img width="678" alt="image" src="https://user-images.githubusercontent.com/3596602/131478850-d7db8d51-78e6-4a1a-b4f6-5c528ec8359e.png">

2021-08-31 09:35 UTC, tiero commented on blog/2021-07-13-tdex-terraform-automation.md
> +$ chmod +x deploy.sh
is it in `terabox` folder? as per https://github.com/tdex-network/tdex-box/pull/16

2021-08-31 13:30 UTC, tiero commented
Looks like you are pushing with wrong git user locally (ie. no PGP attached to that) @kcoax

2021-08-31 13:32 UTC, tiero commented
still not looking good with markdown table

2021-08-31 13:53 UTC, merged